version: "3"
services:
  ui:
    image: swaggerapi/swagger-ui:v4.1.3
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./nslookup-prod-oas30.yaml:/usr/share/nginx/html/nslookup-prod-oas30.yaml
    environment:
      API_URL: nslookup-prod-oas30.yaml
